<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="indirections" nsURI="http://palladiosimulator.org/Indirections/1.0"
    nsPrefix="org.palladiosimulator.indirections">
  <eSubpackages name="actions" nsURI="http://palladiosimulator.org/Indirections/Actions/1.0"
      nsPrefix="org.palladiosimulator.indirections.actions"/>
  <eSubpackages name="system" nsURI="http://palladiosimulator.org/Indirections/System/1.0"
      nsPrefix="org.palladiosimulator.indirections.system">
    <eClassifiers xsi:type="ecore:EClass" name="StatefulResource"/>
    <eClassifiers xsi:type="ecore:EClass" name="Queue"/>
    <eClassifiers xsi:type="ecore:EClass" name="Operator" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="inputPorts"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="composition" nsURI="http://palladiosimulator.org/Indirections/Composition/1.0"
      nsPrefix="org.palladiosimulator.indirections.composition"/>
  <eSubpackages name="repository" nsURI="http://palladiosimulator.org/Indirections/Repository/1.0"
      nsPrefix="org.palladiosimulator.indirections.repository"/>
  <eSubpackages name="datatypes" nsURI="http://palladiosimulator.org/Indirections/Datatypes/1.0"
      nsPrefix="org.palladiosimulator.indirections.datatypes">
    <eClassifiers xsi:type="ecore:EEnum" name="Scheduling">
      <eLiterals name="FirstInFirstOut"/>
      <eLiterals name="LastInFirstOut" value="1"/>
      <eLiterals name="Priority" value="2"/>
      <eLiterals name="Random" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="PutPolicy">
      <eLiterals name="Blocking" literal=""/>
      <eLiterals name="DiscardFirstIn" value="1"/>
      <eLiterals name="DiscardLastIn" value="2"/>
      <eLiterals name="DiscardIncoming" value="3"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
